#!/bin/bash

if [ "$EUID" -ne 0 ]
then
    echo -e "\e[101m\e[97m============================================\e[39m\e[49m"
    echo -e "\e[101m\e[97m==          Must be run as root!          ==\e[39m\e[49m"
    echo -e "\e[101m\e[97m============================================\e[39m\e[49m"
fi
